server:
  port: 8080

spring:
  datasource:
    username: dagu
    password: Tony6666
    url: jdbc:mysql://81.68.234.49:3306/nia?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mybatis:
    cofiguration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #      mapper-location : com.bjtu.dao/*.xml
    type-aliases-package: com.bjtu.emoive.dao # ?????
    mapUnderscoreToCamelCase: true